// aprendiendo-vue/src/components/SidebarComponent.vue
<template>
  <aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
      <h3>Puedes hacer esto</h3>
      <a href="#" class="btn btn-success">Crear Artículo</a>
    </div>
    <div id="search" class="sidebar-item">
      <h3>Buscador</h3>
      <p>Encuentra el artículo que buscas.</p>
      <form>
        <input type="text" name="search" />
        <input type="submit" class="btn" name="submit" value="Buscar" />
      </form>
    </div>
  </aside>
</template>
<script>
export default {
  name: "SlidebarComponent"
};
</script>

// AprendiendoAngular/src/app/components/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {

  public searchString: String;

  constructor(
    private _router: Router,
    private _route: ActivatedRoute
  ){

   }

  ngOnInit(): void {
  }

  goSearch(){

    if(this.searchString){

      this._router.navigate(['/buscar', this.searchString]);

    }

  }

}

<aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
        <h3>Puedes hacer esto</h3>
        <a href="#" class="btn btn-success">Crear Artículo</a>
    </div>
    <div id="search" class="sidebar-item">
        <h3>Buscador</h3>
        <p>Encuentra el artículo que buscas.</p>
        <form #searchForm="ngForm" (ngSubmit)="goSearch()">
            <input type="text" name="search" [(ngModel)]="searchString">
            <input type="submit" class="btn" name="submit" value="Buscar">
        </form>
    </div>
</aside>
