// AprendiendoAngular/src/app/components/articles/articles.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Global } from '../../services/global';
import { Article } from '../../models/article';

@Component({
  selector: 'app-articles',
  templateUrl: './articles.component.html',
  styleUrls: ['./articles.component.css']
})
export class ArticlesComponent implements OnInit {

  @Input() articles: Article[];
  public url: string;

  constructor() { 
    this.url = Global.url;
  }

  ngOnInit(): void {
    
  }

}

<div class="loading" *ngIf="articles && articles.length == 0">
    No hay Artículos que coincidan con la búsqueda, inténtalo más tarde :)
</div>

<div class="loading" *ngIf="!articles">
    Cargando Artículos...
</div>


<div id="articles" *ngIf="articles">
    <article class="article-item" id="article-template" *ngFor="let article of articles">
        <div class="image-wrap">
            <!--https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR-nC2smsN7PDcLUxGxSWkMYvbGvqkTzdDXGA&usqp=CAU-->
            <img src="{{ url+'get-image/'+article.image }}" alt="{{ article.title }}" *ngIf="article.image != null">
            <img src="assets/images/default.png" alt="{{ article.title }}" *ngIf="article.image == null">
        </div>

        <h2>{{ article.title }}</h2>
        <span class="date">
            <!-- amLocale y amTimeAgo son pipes que tenemos gracias a instalar angular2-moment y añadirlo a los imports de nuestro app.module -->
            {{ article.date | amLocale: 'es' | amTimeAgo }}
        </span>
        <a [routerLink]="['/blog/articulo', article._id ]">Leer más</a>
        <div class="clearfix"></div>
    </article>
</div>

// aprendiendo-vue/src/components/ArticlesComponent.vue
<template>

  <div id="article-list" v-if="articles && articles.length >= 1">
    <article
      class="article-item"
      v-for="article in articles"
      :key="article._id"
    >
      <div class="image-wrap">
        <img
          :src="url + 'get-image/' + article.image"
          :alt="article.title"
          v-if="article.image"
        />
        <img
          src="../assets/images/default.png"
          :alt="article.title"
          v-if="!article.image"
        />
      </div>

      <h2>
        <routerLink :to="{ name: 'article', params: { id: article._id }}">
          {{ article.title }}
        </routerLink>
        </h2>
      <span class="date"> {{ article.date | moment("from", "now") }} </span>
      <routerLink :to="{ name: 'article', params: { id: article._id }}">Leer más</routerLink>
      <div class="clearfix"></div>
    </article>
  </div>
  <div v-else-if="articles && articles.length < 1">
    <b>No hay artículos para mostrar en este momento.</b>
  </div>
  <div v-else>
    <b>Cargando...</b>
  </div>
</template>
<script>
import Global from '../Global';

export default {
  name: "ArticlesComponent",
  props: ["articles"],
  data(){
      return{
          url: Global.url
      }
  }
};
</script>
