// AprendiendoAngular/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import Swal from 'sweetalert2';
import { ArticleService } from '../../services/article.service';
//Para coger el parámetro de la URL
import { Router, ActivatedRoute, Params } from '@angular/router';
import { Article } from '../../models/article';
import { Global } from '../../services/global';

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticleService]
})
export class ArticleComponent implements OnInit {

  public article: Article;
  public url: string;

  constructor(
    private _articleService: ArticleService,
    private _route: ActivatedRoute,
    private _router: Router
  ) {
    this.url = Global.url;
  }

  ngOnInit(): void {

    //Recogemos el dato que nos llega de la URL
    this._route.params.subscribe(params => {
      let id = params['id'];

      //Lamada AJAX al Backend
      this._articleService.getArticle(id).subscribe(
        response => {
          if (response.article) {
            console.log(response.article);
            this.article = response.article;
          } else {
            this._router.navigate(['/404']);
          }
        },
        error => {
          console.log(error);
          this._router.navigate(['/404']);
        }
      );

    });

  }

  delete(id) {

    //ALERTA
    Swal.fire({
      title: '¿Estás seguro?',
      text: "Si aceptas se eliminará para siempre.",
      icon: 'warning',
      showCancelButton: true,
      showCloseButton: true,
      confirmButtonColor: '#179613',
      cancelButtonColor: '#C91515',
      confirmButtonText: '¡Eliminalo!',
      cancelButtonText: 'Cancelar'
    }).then((result) => {
      if (result.isConfirmed) {
        //Borramos
        this._articleService.delete(id).subscribe(
          response => {
            Swal.fire(
              '!Artículo Eliminado¡',
              'El artículo ha sido eliminado correctamente.',
              'success'
            ).then((result2) => {
              if (result2.isConfirmed) {
                this._router.navigate(['/blog']);
              }
            });
          },
          error => {
            console.log(error);
            //ALERTA
            Swal.fire({
              icon: 'error',
              title: 'Fallo en la Eliminación',
              text: 'Error al borrar el artículo: ' + error
            }).then((result) => {
              if (result.isConfirmed) {
                this._router.navigate(['/blog']);
              }
            });
            
          }
        );

      }//end if
    });


  }

}

<div class="center" *ngIf="article">
    <section id="content">

        <article class="article-item article-detail">

            <div class="image-wrap" [ngStyle]=
            "{
                'background-image': 'url('+url+'get-image/'+article.image+')',
                'background-position': 'center',
                'background-size': 'cover'
            }"  
            *ngIf="article.image != null"></div>
            <div class="image-wrap" [ngStyle]=
            "{
                'background-image': 'url(assets/images/default.png)',
                'background-position': 'center',
                'background-size': 'cover'
            }" 
            *ngIf="article.image == null"></div>
                <!--<img src="{{ url+'get-image/'+article.image }}" alt="{{ article.title }}" *ngIf="article.image != null">
                <img src="assets/images/default.png" alt="{{ article.title }}" *ngIf="article.image == null">-->
            
            <h1 class="sub-header"> {{ article.title }}</h1>
            <span class="date">
                <!-- amLocale y amTimeAgo son pipes que tenemos gracias a instalar angular2-moment y añadirlo a los imports de nuestro app.module -->
                {{ article.date | amLocale: 'es' | amTimeAgo }}
            </span>
            <p>
                {{ article.content }}
            </p>

            <div class="buttons">
                <a [routerLink]="['/blog/editar', article._id]" class="btn btn-warning">Editar</a>
                <a (click)="delete(article._id)" class="btn btn-danger">Eliminar</a>
            </div>

            <div class="clearfix"></div>
        </article>


    </section>
    <!-- Sidebar -->
    <app-sidebar></app-sidebar>
    <div class="clearfix"></div>
</div>

// aprendiendo-vue/src/components/ArticleComponent.vue
<template>
  <div class="general" v-if="article">
    <SliderComponent :titulo="article.title" />
    <div class="center">
      <section id="content">
        <article class="article-item article-detail">
          <div class="image-wrap" v-if="article.image">
            <img
              :src="url + 'get-image/' + article.image"
              :alt="article.title"
            />
          </div>
          <h1 class="sub-header">{{ article.title }}</h1>
          <span class="date"> {{ article.date | moment("from", "now") }} </span>
          <p>
            {{ article.content }}
          </p>
          <div class="clearfix"></div>
          <a class="btn btn-danger" @click="deleteArticle(article._id)"
            >Eliminar</a
          >
          <routerLink
            :to="'/editar-articulo/' + article._id"
            class="btn btn-warning"
            >Editar</routerLink
          >
        </article>
      </section>
      <SidebarComponent />
      <div class="clearfix"></div>
    </div>
  </div>
</template>
    
<script>
//Importamos axios para hacer peticiones AJAX al backend
import axios from "axios";
import SliderComponent from "./SliderComponent.vue";
import SidebarComponent from "./SidebarComponent.vue";
import Global from "../Global";
//importamos sweetalert2
import swal from "sweetalert2";

export default {
  name: "ArticleComponent",
  components: {
    SliderComponent,
    SidebarComponent,
  },
  data() {
    return {
      url: Global.url,
      article: null,
    };
  },
  mounted() {
    var articleID = this.$route.params.id;
    this.getArticle(articleID);
  },
  methods: {
    getArticle(articleID) {
      axios.get(this.url + "article/" + articleID).then((res) => {
        if (res.data.status == "success") {
          this.article = res.data.article;
        }
      });
    },
    deleteArticle(articleID) {
      const swalWithBootstrapButtons = swal.mixin({
        customClass: {
          confirmButton: "btn-danger",
        },
        buttonsStyling: true,
      });
      swalWithBootstrapButtons
        .fire({
          title: "ATENCIÓN",
          html:
            "<p>¿Está seguro de que quiere eliminar el artículo?</p> <p>Será eliminado <b>definitivamente</b> del sistema.</p>",
          icon: "warning",
          confirmButtonText: "¡Sí, eliminalo!",
          showCancelButton: true,
          cancelButtonText: "Cancelar"
        })
        .then((result) => {
          /* Read more about isConfirmed, isDenied below */
          if (result.isConfirmed) {
            axios.delete(this.url + "/article/" + articleID).then((res) => {
              if (res.data.status == "success") {
              swal
                .fire({
                  title: "Eliminación Correcta",
                  text: "El artículo ha sido eliminado correctamente.",
                  icon: "success",
                  confirmButtonText: "¡Genial!",
                })
                .then((result) => {
                  /* Read more about isConfirmed, isDenied below */
                  if (result.isConfirmed) {
                    //redireccionamos al blog
                    this.$router.push("/blog/");
                  }
                });
              }
            });
          }else if(result.isDismissed){
            swal
                .fire({
                  title: "Eliminación Cancelada",
                  html: "<p>No te preocupes, no se ha borrado nada.</p><p></b><b>:)</p>",
                  icon: "success",
                  confirmButtonText: "¡Genial!",
            })
          }
        });
    },
  },
};
</script>
