// AprendiendoAngular/src/app/components/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';
import { User } from 'src/app/models/user';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {

  public user: User;

  //EVENTOS
  public campo: string

  constructor() {

    this.user = {
      "name": '',
      "surnames": '',
      "biography": '',
      "gender": ''
    };


  }

  ngOnInit(): void {
  }


  onSubmit() {
    
    console.log(this.user);

  }

  hasDadoClick(){
    alert('¡Has usado el evento click para llamar a la función hasDadoClick()!');
  }

  hasSalido(campo){
    if(campo == '' || campo == undefined){
      alert('¡Has usado el evento blur para llamar a la función hasSalido()!\<br>\ El campo está vacío.');
    }else{
      alert('¡Has usado el evento blur para llamar a la función hasSalido()!\<br>\ El campo está relleno: '+ campo);
    }
   
  }

  hasDadoEnter(){
    alert('¡Has usado el evento keyUp.enter para llamar a la función hasDadoEnter()!');
  }

}

<!-- Slider -->
<app-slider [nombreEjemplo]="'Formulario de Contacto'" [size]="'small'"></app-slider>
<div class="center">
    <section id="content">
        <h1 class="sub-header">Formulario de Contacto</h1>

        <form action="#" class="mid-form" #userForm="ngForm" (ngSubmit)="onSubmit()">
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="user.name" required
                    pattern="[a-zA-Z]+[^0-9]*">
                <!-- TIENE QUE PONERSE EL NOMBRE CON EL QUE DEFINIMOS EL CAMPO EN ANGULAR (#nombre="ngModel") -->
                <small *ngIf="!nombre.valid && nombre.touched">El campo nombre no es válido.</small>
            </div>
            <div class="form-group">
                <label for="apellidos">Apellidos</label>
                <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)]="user.surnames" required
                    pattern="[a-zA-Z]+[^0-9]*">
                <small *ngIf="!apellidos.valid && apellidos.touched">El campo apellidos no es válido.</small>
            </div>
            <div class="form-group">
                <label for="bio">Biografía</label>
                <textarea name="bio" cols="30" rows="10" #biografia="ngModel" [(ngModel)]="user.biography"
                    required></textarea>
                <small *ngIf="!biografia.valid && biografia.touched">El campo biografía no es válida.</small>
            </div>
            <div class="form-group radiobuttons">
                <input type="radio" name="genero" value="mujer" #genero="ngModel" [(ngModel)]="user.gender" required />
                Mujer
                <input type="radio" name="genero" value="hombre" #genero="ngModel" [(ngModel)]="user.gender" /> Hombre
                <input type="radio" name="genero" value="otro" #genero="ngModel" [(ngModel)]="user.gender" /> Otro
                <small *ngIf="!genero.valid && genero.touched">El campo género no es válido.</small>
            </div>
            <div class="clearfix"></div>
            <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid">
        </form>

        <h2 class="sub-header">Eventos</h2>

        <div>
            <span>Evento Click:</span>
            <br>
            <button (click)="hasDadoClick()">¡Dale Click!</button>
        </div>
        <div>
            <span>Evento Blur: (sal del campo)</span>
            <input type="text" [(ngModel)]="campo" (blur)="hasSalido(campo)">
            {{ campo }}
        </div>
        <div>
            <span>Envento KeyUp (dale a enter): </span>
            <input type="text" [(ngModel)]="campo" (keyUp.enter)="hasDadoEnter()">
        </div>


    </section>
    <!-- Sidebar -->
    <app-sidebar></app-sidebar>
    <div class="clearfix"></div>
</div>

// aprendiendo-vue/src/components/FormularioComponent.vue
<template>
  <div class="general">
    <SliderComponent titulo="Formulario" />
    <div class="center">
      <section id="content">
        <h2 class="sub-header">Formulario</h2>
        <form action="#" class="mid-form" @submit.prevent="mostrarUsuario">
          <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" name="nombre" v-model="user.nombre" />
            <div class="error" v-if="this.submitted && !$v.user.nombre.required">El nombre es requerido.</div>
            <div class="error" v-if="this.submitted && !$v.user.nombre.alpha">El nombre solo admite caracteres.</div>
          </div>
          <div class="form-group">
            <label for="apellidos">Apellidos</label>
            <input type="text" name="apellidos" v-model="user.apellidos" />
            <div class="error" v-if="this.submitted && !$v.user.apellidos.required">Los apellidos son requeridos.</div>
            <div class="error" v-if="this.submitted && !$v.user.apellidos.alpha">Los apellidos solo admiten caracteres.</div>
          </div>
          <div class="form-group">
            <label for="bio">Biografía</label>
            <textarea
              name="bio"
              cols="30"
              rows="10"
              v-model="user.bio"
            ></textarea>
            <div class="error" v-if="this.submitted && !$v.user.bio.required">La biografía es requerida.</div>
            <div class="error" v-if="this.submitted && !$v.user.bio.minLength">La biografía requeride un mínimo de {{$v.user.bio.$params.minLength.min}} caracteres.</div>
          </div>
          <div class="form-group radiobuttons">
            <input
              type="radio"
              name="genero"
              value="mujer"
              v-model="user.genero"
            />
            Mujer
            <input
              type="radio"
              name="genero"
              value="hombre"
              v-model="user.genero"
            />
            Hombre
            <input
              type="radio"
              name="genero"
              value="otro"
              v-model="user.genero"
            />
            Otro
            <div class="error" v-if="this.submitted && !$v.user.genero.required">El genero es requerido.</div>
          </div>
          <div class="clearfix"></div>
          <input type="submit" value="Enviar" class="btn btn-success" />
        </form>
        <p v-if="user.nombre && user.apellidos && user.bio && user.genero">
          {{ user.nombre + "  " + user.apellidos }}
          <br />
          {{ user.bio }}
          <br />
          {{ user.genero }}
        </p>
      </section>
      <SidebarComponent />
      <div class="clearfix"></div>
    </div>
  </div>
</template>
<script>
//https://vuelidate.js.org/#getting-started; HAY QUE IMPORTAR VUELIDATE EN EL main.js Y HACERLE UN USE PARA QUE NO PETE
import { required, alpha, minLength } from 'vuelidate/lib/validators';
import SliderComponent from "./SliderComponent.vue";
import SidebarComponent from "./SidebarComponent.vue";


export default {
  name: "FormularioComponent",
  components: {
    SliderComponent,
    SidebarComponent,
  },
  data() {

    return {
      submitted: false,
      user: {
        nombre: "",
        apellidos: "",
        bio: "",
        genero: "",
      },
    };
  },
   validations: {
     user: {
      nombre: {
        required,
        alpha
      },
      apellidos: {
        required,
        alpha
      },
      bio: {
        required,
        minLength: minLength(10)
      },
      genero: {
        required
      }
    }
  },
  methods: {
    mostrarUsuario() {
      console.log(this.user);
      this.submitted = true;

      this.$v.$touch();
      if(this.$v.$invalid) {
        return false;
      }
      alert('¡¡¡Validación Pasada con Éxito!!!');
    },
  }
};
</script>
