// AprendiendoAngular/src/app/components/pelicula/pelicula.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Pelicula } from 'src/app/models/pelicula';


@Component({
  selector: 'app-pelicula',
  templateUrl: './pelicula.component.html',
  styleUrls: ['./pelicula.component.css']
})
export class PeliculaComponent implements OnInit {

  @Input() film: Pelicula;
  @Input() i: number;
  @Input() estreno_format: string;
  @Input() hace: number;

  //Output es para enviar datos del componente hijo al componente padre
  @Output() MarcarFavorita = new EventEmitter();

  constructor() { }

  ngOnInit(): void {
  }

  seleccionar(event, film){
    this.MarcarFavorita.emit({
      "pelicula": film
    });
  }

}

<article class="article-item">
    <div class="image-wrap">
        <img src="{{ film.image }}" alt="{{ film.title }}">
    </div>

    <h2>{{ i+1 }} - {{ film.title }}</h2>
    <span class="date" [style.color]="film.year.getFullYear() > 2016 ? 'green' : 'red'" *ngIf="hace[i] >= 0">
        Se estrenó el {{ estreno_format[i] }}, hace {{ hace[i] }} años.
    </span>
    <span class="date" [style.color]="film.year.getFullYear() > 2016 ? 'green' : 'red'" *ngIf="hace[i] < 0">
        Se estrenará el {{ estreno_format[i] }}, en {{ -hace[i] }} años.
    </span>
    <!-- [class.year-green]="film.year > 2016" [class.year-red]="film.year < 2016" -->
    <span class="year" [ngClass]="{
                            'year-green': film.year.getFullYear() > 2016 ,
                            'year-red': film.year.getFullYear() < 2016 
                        }">
        {{ film.year.getFullYear() }}
    </span>
    <!--<a href="article.html">Leer más</a>-->
    <button (click)="seleccionar($event, film)">
        Seleccionar Favorita
    </button>
    <div class="clearfix"></div>
</article>

// aprendiendo-vue/src/components/PeliculaComponent.vue
<template>
    <article class="article-item" id="article-template">
        <div class="image-wrap">
            <!-- v-bind: o : aseacas, es lo mismo -->
          <img
            v-bind:src="pelicula.image"
            v-bind:alt="pelicula.title"
            :title="pelicula.title"
            />
        </div>

        <h2>{{ pelicula.title }}</h2>
        <span :class="{
            dateyellow: pelicula.year < 2015,
            dategreen: pelicula.year >= 2015,
            datered: pelicula.year == 2017
        }"> {{ pelicula.year }} </span>
        <a href="article.html">Leer más</a>
        <!-- @click="" o v-on:click=""-->
        <input type="button" value="Marcar como favorita"
            @click="pasarFavoritaAlPadre(pelicula)"
        />
        <div class="clearfix"></div>
      </article>
</template>
<script>
export default {
    name: 'Pelicula',
    props: ['pelicula'],
    methods: {
        pasarFavoritaAlPadre(pelicula){
            //Emitimos la pelicula al elemento padre
            this.$emit('favorita', pelicula)
        }
    }
    
}
</script>
